vim.o.wildignore = vim.o.wildignore .. '*.pyc,*.o,*.swp,*.DS_Store'
vim.wo.number = true
vim.o.mouse = 'a'
vim.o.guicursor = 'n-v-c-sm:block'
vim.o.clipboard = 'unnamedplus' -- sync clipboard between OS and nvim
vim.o.breakindent = true        -- enable break indent
vim.o.undofile = true           -- save undo history
vim.o.hlsearch = true           -- highlight search
vim.o.incsearch = true
vim.o.ignorecase = true         -- case insensitive search
vim.o.smartcase = true
vim.wo.signcolumn = 'yes'
vim.o.updatetime = 250                 -- decrease update time
vim.o.timeoutlen = 300
vim.o.completeopt = 'menuone,noselect' -- better completion experience
vim.o.termguicolors = true             -- make sure the terminal supports this
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.scrolloff = 5
